# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

# get icons here: https://tabler-icons.io

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/amerkurev/python-study"

[social.params]
icon = "brand-github"


[[social]]
identifier = "telegram"
name = "Telegram"
url = "https://t.me/pystudy"

[social.params]
icon = "brand-telegram"


[[social]]
identifier = "medium"
name = "Medium"
url = "https://medium.com/@apps.merkurev"

[social.params]
icon = "brand-medium"


[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/amerkurev"

[social.params]
icon = "brand-linkedin"


[[social]]
identifier = "rss"
name = "RSS"
url = "https://python.study/index.xml"

[social.params]
icon = "rss"
